apiVersion: v1
kind: Service
metadata:
  name: app-frontend-svc
  namespace: k8s-ingress
  labels:
    app: app-frontend
    lab: k8s-03
spec:
  type: ClusterIP
  selector:
    app: app-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: api-backend-svc
  namespace: k8s-ingress
  labels:
    app: api-backend
    lab: k8s-03
spec:
  type: ClusterIP
  selector:
    app: api-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: admin-dashboard-svc
  namespace: k8s-ingress
  labels:
    app: admin-dashboard
    lab: k8s-03
spec:
  type: ClusterIP
  selector:
    app: admin-dashboard
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
