apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: myapp-staging

namespace: staging

commonLabels:
  environment: staging

resources:
  - ../../base

patches:
  - path: replica-patch.yaml

images:
  - name: 123456789012.dkr.ecr.us-east-1.amazonaws.com/myapp
    newTag: v1.1.0
