apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
  namespace: k8s-storage
  labels:
    app: persistent-app
    lab: k8s-02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi             # Request 5Gi initially (can expand later)
  storageClassName: fast-storage  # References the StorageClass
  # No need to create a PV manually -- the StorageClass provisioner
  # will dynamically create a PV that matches this claim
