apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ecommerce-service.fullname" . }}
  labels:
    {{- include "ecommerce-service.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "ecommerce-service.selectorLabels" . | nindent 6 }}
