apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-service.fullname" . }}
  labels:
    {{- include "ecommerce-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "ecommerce-service.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
