apiVersion: v1
kind: Pod
metadata:
  name: qos-burstable
  namespace: team-a
  labels:
    app: qos-demo
    qos-class: burstable
spec:
  containers:
    - name: app
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80
      # Burstable QoS: requests are LESS than limits
      # (or only requests are specified without limits)
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m        # Higher than request -- can "burst"
          memory: 512Mi    # Higher than request -- can "burst"
      # Burstable pods can use more resources than requested
      # but are evicted before Guaranteed pods under pressure
