---
- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true

- name: Restart CloudWatch Agent
  ansible.builtin.command:
    cmd: >-
      /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
      -a fetch-config -m ec2 -s
      -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json
  changed_when: true
