apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: myapp-prod

namespace: prod

commonLabels:
  environment: production

commonAnnotations:
  app.kubernetes.io/part-of: myapp-platform
  support-tier: "tier-1"

resources:
  - ../../base

patches:
  - path: replica-patch.yaml

images:
  - name: 123456789012.dkr.ecr.us-east-1.amazonaws.com/myapp
    newTag: v1.0.5
